Repository halo-dev/plugin-starter, pull requests merged in 2023-05, with the labels that each got.

#9 chore: update license in plugin.yaml
  src/main/resources/plugin.yaml
Labels: approved, kind/improvement, lgtm, release-note-none

#10 refactor: optimizing project structure and configuration
  .editorconfig
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  lib/halo-2.0.0-SNAPSHOT-plain.jar
  src/main/java/run/halo/starter/StarterPlugin.java
  src/main/resources/console/main.js
  src/main/resources/console/style.css
  src/main/resources/plugin.yaml
Labels: approved, lgtm, release-note-none

#11 chore: add halo plugin devtools dependency
  build.gradle
  settings.gradle
  src/main/resources/plugin.yaml
Labels: release-note-none
