Repository halo-dev/plugin-starter, pull requests merged in 2025-06, with the labels that each got.

#53 chore: update ui template
  ui/.editorconfig
  ui/.eslintrc.cjs
  ui/.prettierrc.json
  ui/eslint.config.ts
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/index.ts
  ui/src/views/HomeView.vue
  ui/tsconfig.app.json
  ui/tsconfig.node.json
  ui/tsconfig.vitest.json
  ui/vite.config.ts
Labels: release-note-none

#54 Make sure the processUiResources task is executed after processResources
  build.gradle
  ui/build.gradle
Labels: release-note

#55 docs: add deprecated information in readme
  README.md
Labels: lgtm, release-note-none

#56 Bump Halo devtools to 0.6.1
  build.gradle
Labels: release-note
